add debug info and message

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -60,19 +60,27 @@ pipeline {
     }
     steps {
         withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-            sh '''
-                git config user.email "ankkitraj4@hotmail.com"
-                git config user.name "ankkitraj"
-                BUILD_NUMBER=${BUILD_NUMBER}
-                sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                git commit -m "Update deployment image to version ${BUILD_NUMBER}"
-                git checkout -b feature-branch  # Choose an appropriate branch name
-                git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:feature-branch
-            '''
+            script {
+                echo "Current Git Status:"
+                sh 'git status'
+
+                echo "Configuring Git:"
+                sh 'git config user.email "ankkitraj4@hotmail.com"'
+                sh 'git config user.name "Ankit Raj"'
+
+                echo "Making Changes:"
+                sh "sed -i 's/replaceImageTag/${BUILD_NUMBER}/g' java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml"
+                sh "git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml"
+                sh "git commit -m 'Update deployment image to version ${BUILD_NUMBER}'"
+
+                echo "Checking out Branch:"
+                sh 'git checkout -b feature-branch'
+                sh "git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:feature-branch" || error "Failed to push changes"
+            }
         }
     }
 }
 
-  }
+def error(message) {
+    error(message)
 }
